# Generated by Django 5.2.7 on 2025-10-26 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_chatthread_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatFoundryThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foundry_thread_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foundry",
                        to="api.chatthread",
                    ),
                ),
            ],
        ),
    ]
