version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    working_dir: /app
    volumes:
      - ./backend:/app:ro
      - ./data:/app/data
    expose:
      - "8000"
    environment:
      PYTHONUNBUFFERED: "1"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80" # mapped to 80 inside the frontend container
    volumes:
      - ./frontend:/app:ro

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/frontend.conf:ro
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/conf.d
