from typing import List, Dict, Any, Optional

class DataRepo:
    # Styles
    def list_styles(self) -> List[Dict[str, Any]]: ...
    def create_or_update_style(self, name: str, style: str, example: str) -> Dict[str, Any]: ...
    def delete_style(self, style_id: str) -> None: ...

    # Outputs
    def list_outputs(self, limit: int = 100) -> List[Dict[str, Any]]: ...
    def save_output(self, style_name: str, input_text: str, output_text: str) -> Dict[str, Any]: ...
